#
# Do not delete this file!
# It is used by programs that wish to include the DFXML_WRITER or the DFXML_READER
#

DFXML_WRITER = $(DFXML_SRC_DIR)dfxml_writer.h \
      $(DFXML_SRC_DIR)dfxml_hash_t.h \
      $(DFXML_SRC_DIR)dfxml_cpuid.h \
      $(DFXML_SRC_DIR)dfxml_cpuid.cpp
      
DFXML_READER = $(DFXML_SRC_DIR)dfxml_reader.cpp \
      $(DFXML_SRC_DIR)dfxml_reader.h \
      $(DFXML_SRC_DIR)dfxml_hash_t.h
